name: estudando
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  path_provider: ^2.1.3
  epubx: ^4.0.0
  epub_view: ^3.2.0
  permission_handler: ^11.3.1
  syncfusion_flutter_pdf: ^25.1.39
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
